esp_toml_version = 1.0
firmware_images_url = "https://dl.espressif.com/AE/esp-box/"

supported_apps = ["ESP-BOX_Demo_EN_V0_3_0", "ESP-BOX_Demo_CN_V0_3_0"]

[ESP-BOX_Demo_EN_V0_3_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_Demo_EN_V0.3.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX_Demo_CN_V0_3_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_Demo_CN_V0.3.0.bin"
android_app_url = ""
ios_app_url = ""