esp_toml_version = 1.0
firmware_images_url = "https://dl.espressif.com/AE/esp-box/"

supported_apps = [
    "ESP-BOX-3_Demo_V1_1_1",
    "ESP-BOX-3_ChatGPT_Demo_V1_0",
    "ESP-BOX-3_MATTER_SWITCH_Demo_V1_0",

    "ESP-BOX_Demo_CN_V0_3_0",
    "ESP-BOX_Demo_EN_V0_3_0", 
    "ESP-BOX_Demo_EN_V0_5_0", 
    "ESP-BOX_Demo_CN_V0_5_0",
    "ESP-BOX_ChatGPT_Demo_V1_0",
    "ESP-BOX_USB_Headset_V0_0_1", 
    "ESP-BOX_MATTER_SWITCH_Demo_V1_0",

    "ESP-BOX-Lite_Demo_EN_V0_5_0", 
    "ESP-BOX-Lite_Demo_CN_V0_5_0",
    "ESP-BOX-Lite_ChatGPT_Demo_V1_0",
    "ESP-BOX-Lite_MATTER_SWITCH_Demo_V1_0"
]

[ESP-BOX_Demo_EN_V0_3_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_Demo_EN_V0.3.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX_Demo_CN_V0_3_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_Demo_CN_V0.3.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX_USB_Headset_V0_0_1]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_USB_Headset_V0.0.1.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX_ChatGPT_Demo_V1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_ChatGPT_Demo_V1.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX-Lite_ChatGPT_Demo_V1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_Lite_ChatGPT_Demo_V1.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX-3_ChatGPT_Demo_V1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX-3_ChatGPT_Demo_V1_0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX_Demo_CN_V0_5_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_Demo_CN_V0.5.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX_Demo_EN_V0_5_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_Demo_EN_V0.5.0.bin.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX-Lite_Demo_CN_V0_5_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX-Lite_Demo_CN_V0.5.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX-Lite_Demo_EN_V0_5_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX-Lite_Demo_EN_V0.5.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX-3_Demo_V1_1_1]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX-3_Demo_V1.1.1.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX_MATTER_SWITCH_Demo_V1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_MATTER_SWITCH_Demo_V1.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX-Lite_MATTER_SWITCH_Demo_V1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX_Lite_MATTER_SWITCH_Demo_V1.0.bin"
android_app_url = ""
ios_app_url = ""

[ESP-BOX-3_MATTER_SWITCH_Demo_V1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ESP-BOX-3_MATTER_SWITCH_Demo_V1.0.bin"
android_app_url = ""
ios_app_url = ""
