# Copyright 2022 Espressif Systems (Shanghai) PTE LTD
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow build examples, store the artifacts and deploy them to github pages.
# Generates the launchpad configuration file that can be used with the url.

name: "Build examples to github pages"

on:
    push:
        branches:
        - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.1
    strategy:
      matrix:
        build-dir: [
          'chatgpt_demo',
          'factory_demo',
          'image_display',
          'lv_demos',
          'mp3_demo',
          'usb_camera_lcd_display',
          'usb_headset',
          'watering_demo']
        boards: ['sdkconfig.ci.box', 'sdkconfig.ci.box-lite', 'sdkconfig.ci.box-3']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: mkdir -p images
      - name: Build examples
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          cd $GITHUB_WORKSPACE/examples/${{matrix.build-dir}}
          if [ -e "${{matrix.boards}}" ]; then
            rm -rf sdkconfig build sdkconfig.defaults
            cp ${{matrix.boards}} sdkconfig.defaults
            # idf.py -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;${{matrix.boards}}" reconfigure
          fi

          if [[ ${{matrix.build-dir}} == usb_camera_lcd_display ]]; then
            if [[ ${{matrix.boards}} == sdkconfig.ci.box-3 ]]; then
              idf.py build
              cd build
              esptool.py --chip esp32s3 merge_bin -o "$GITHUB_WORKSPACE/images/${{matrix.build-dir}}_${{matrix.boards}}.bin" @flash_args
            else
              echo "Skipping build for ${{matrix.build-dir}} with ${{matrix.boards}}"
            fi
          elif [[ ${{matrix.build-dir}} == chatgpt_demo ]]; then
            idf.py build

            cd factory_nvs
            rm -rf sdkconfig build sdkconfig.defaults
            cp ${{matrix.boards}} sdkconfig.defaults
            # idf.py -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;${{matrix.boards}}" reconfigure
            idf.py build

            cd ../
            esptool.py --chip ESP32-S3 merge_bin \
            -o "$GITHUB_WORKSPACE/images/${{matrix.build-dir}}_${{matrix.boards}}.bin" \
            --flash_mode dio --flash_freq 80m --flash_size 16MB \
            0x0 build/bootloader/bootloader.bin \
            0x8000 build/partition_table/partition-table.bin \
            0xd000 build/ota_data_initial.bin \
            0x10000 build/chatgpt_demo.bin \
            0x900000 build/storage.bin \
            0xb00000 build/srmodels/srmodels.bin \
            0x700000 factory_nvs/build/factory_nvs.bin
          else
            idf.py build
            cd build
            esptool.py --chip esp32s3 merge_bin -o "$GITHUB_WORKSPACE/images/${{matrix.build-dir}}_${{matrix.boards}}.bin" @flash_args
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-images
          path: images/

  job2:
    runs-on: ubuntu-latest
    container: espressif/esp-matter:latest
    strategy:
      matrix:
        build-dir: ['matter_switch']
        boards: ['sdkconfig.ci.box', 'sdkconfig.ci.box-lite', 'sdkconfig.ci.box-3']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: mkdir -p images
      - name: Build examples
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          . $ESP_MATTER_PATH/export.sh
          cd $GITHUB_WORKSPACE/examples/${{matrix.build-dir}}

          rm -rf sdkconfig build sdkconfig.defaults
          cp ${{matrix.boards}} sdkconfig.defaults
          # idf.py -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;${{matrix.boards}}" reconfigure
          idf.py set-target esp32s3 build
          cd build
          esptool.py --chip esp32s3 merge_bin -o "$GITHUB_WORKSPACE/images/${{matrix.build-dir}}_${{matrix.boards}}.bin" @flash_args

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-images
          path: images/

  deploy:
    needs: [job1, job2]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Download builds
        uses: actions/download-artifact@v3
        with:
          name: build-images
          path: images/

      - name: generate launchpad config
        run: |
          cd images/
          ls
          $GITHUB_WORKSPACE/tools/launchpad/rename.sh $GITHUB_WORKSPACE
          ls
          $GITHUB_WORKSPACE/tools/launchpad/generate_launchpad_config.sh

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: images/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
